# This is used is checking if the model will compile, set every value to 2

test_scaled_point_data = [{'cx': 127, 'cy': 213, 'label': 'L_Toe'},
                          {'cx': 136, 'cy': 204, 'label': 'L_Ankle'},
                          {'cx': 117, 'cy': 172, 'label': 'L_Knee'},
                          {'cx': 133, 'cy': 160, 'label': 'L_Pelvis'},
                          {'cx': 143, 'cy': 160, 'label': 'L_Hip'},
                          {'cx': 121, 'cy': 126, 'label': 'L_Shoulder'},
                          {'cx': 100, 'cy': 127, 'label': 'L_Elbow'},
                          {'cx': 83, 'cy': 123, 'label': 'L_Wrist'},
                          {'cx': 109, 'cy': 204, 'label': 'R_Toe'},
                          {'cx': 120, 'cy': 198, 'label': 'R_Ankle'},
                          {'cx': 108, 'cy': 168, 'label': 'R_Knee'},
                          {'cx': 127, 'cy': 159, 'label': 'R_Pelvis'},
                          {'cx': 138, 'cy': 155, 'label': 'R_Hip'},
                          {'cx': 117, 'cy': 122, 'label': 'R_Shoulder'},
                          {'cx': 101, 'cy': 123, 'label': 'R_Elbow'},
                          {'cx': 84, 'cy': 122, 'label': 'R_Wrist'},
                          {'cx': 140, 'cy': 149, 'label': 'Bottom_spine'},
                          {'cx': 133, 'cy': 137, 'label': 'Middle_spine'},
                          {'cx': 123, 'cy': 119, 'label': 'Top_Spine'},
                          {'cx': 36, 'cy': 193, 'label': 'L_Toe'},
                          {'cx': 61, 'cy': 179, 'label': 'L_Ankle'},
                          {'cx': 29, 'cy': 151, 'label': 'L_Knee'},
                          {'cx': 88, 'cy': 147, 'label': 'L_Pelvis'},
                          {'cx': 72, 'cy': 132, 'label': 'L_Hip'},
                          {'cx': 72, 'cy': 96, 'label': 'L_Shoulder'},
                          {'cx': 15, 'cy': 101, 'label': 'L_Elbow'},
                          {'cx': 44, 'cy': 68, 'label': 'L_Wrist'},
                          {'cx': 164, 'cy': 190, 'label': 'R_Toe'},
                          {'cx': 135, 'cy': 176, 'label': 'R_Ankle'},
                          {'cx': 171, 'cy': 149, 'label': 'R_Knee'},
                          {'cx': 110, 'cy': 147, 'label': 'R_Pelvis'},
                          {'cx': 123, 'cy': 131, 'label': 'R_Hip'},
                          {'cx': 122, 'cy': 93, 'label': 'R_Shoulder'},
                          {'cx': 179, 'cy': 96, 'label': 'R_Elbow'},
                          {'cx': 151, 'cy': 67, 'label': 'R_Wrist'},
                          {'cx': 99, 'cy': 135, 'label': 'Bottom_spine'},
                          {'cx': 98, 'cy': 112, 'label': 'Middle_spine'},
                          {'cx': 97, 'cy': 96, 'label': 'Top_Spine'}]

test_correctness_data = [
    1, 1
]
